services:
  postgres:
    image: postgres:16
    container_name: materie-postgres
    restart: always
    environment:
      POSTGRES_USER: scuola
      POSTGRES_PASSWORD: scuola_pass
      POSTGRES_DB: db_materie
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scuola -d db_materie"]
      interval: 10s
      timeout: 5s
      retries: 5

  materie-service:
    build: .
    container_name: materie-service
    ports:
      - "80:9000"
    environment:
      SPRING_PROFILES_ACTIVE: sviluppo
      SERVER_PORT: 9000
      DB_URL: jdbc:postgresql://postgres:5432/db_materie
      DB_USER: scuola
      DB_PASSWORD: scuola_pass
      JWT_CHIAVE_SEGRETA: 4f7dca55901487f2df866a449e1716db88181900c248dcc83fe96fd3e70deb6a
    depends_on:
      postgres:
        condition: service_healthy
