name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:

  # Build, test e analisi statica
  build:
    name: Build, Test e Analisi Statica
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: db_materie
          POSTGRES_USER: scuola
          POSTGRES_PASSWORD: scuola_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # validate → Checkstyle
      # compile  → compilazione
      # test     → test unitari + JaCoCo report
      # package  → crea il JAR
      # verify   → JaCoCo check + PMD + SpotBugs
      - name: Build, test e analisi statica
        run: ./mvnw verify
        env:
          DB_URL: jdbc:postgresql://localhost:5432/db_materie
          DB_USER: scuola
          DB_PASSWORD: scuola_pass
          SPRING_PROFILES_ACTIVE: sviluppo
